on:
  push:
    branches:
      - staging
name: ðŸš€ Deploy website on push to 2 branch
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: node16
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp_server: testing-git-hub-actions.vercel.app
        ftp_username: ${{ secrets.ftp_username }}
        ftp_password: ${{ secrets.ftp_password }}
        